version: "3"
services:
  captcha:
    build: .
    container_name: "captcha_keras"
    ports:
      - "5000:5000"
    volumes:
      - /tmp/captcha:/user/source/app/reports
    networks:
      - development-network

networks:
  development-network:
    driver: bridge