FROM python:3.6

WORKDIR /user/source/app

COPY setup.py ./
COPY Project/__init__.py ./Project/__init__.py

RUN pip install -r requirements.txt

COPY . .

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 app:app